import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PrimeReactProvider, AppendToType } from "primereact/api";

import "@/app/globals.css";
import StoreProvider from "@/store/StoreProvider";
import GlobalToast from "../_components/GlobalToast";
import AppMain from "./AppMain";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

const value = {
  appendTo: 'self' as AppendToType,
  // ripple: true,
  locale: 'en',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <StoreProvider>
      <html lang="en" className="bg-[#EFF3F8]">
        <body className={inter.className}>
          <PrimeReactProvider value={value}>
            <GlobalToast />
            <AppMain>{children}</AppMain>
          </PrimeReactProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
